# Generated by Django 5.2.10 on 2026-01-30 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name_ar', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('company_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('INTERNET', 'Internet')], default='MOBILE', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name_ar'],
                'indexes': [models.Index(fields=['is_active'], name='sales_telec_is_acti_2ae0fe_idx'), models.Index(fields=['company_type'], name='sales_telec_company_6e41cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='RechargeDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('MOBILE', 'Mobile Recharge'), ('INTERNET', 'Internet Card')], max_length=20)),
                ('value', models.PositiveIntegerField()),
                ('cost_to_company', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_to_agent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_to_customer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='sales.telecomcompany')),
            ],
            options={
                'ordering': ['company', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('PRINTED', 'Printed'), ('CONFIRMED', 'Confirmed')], db_index=True, default='PRINTED', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('receipt_expires_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_reissue_count', models.PositiveIntegerField(default=0)),
                ('receipt_reissue_limit', models.PositiveIntegerField(default=3)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('POS', 'POS')], default='WEB', max_length=10)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('offline_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.telecomcompany')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sales.rechargedenomination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REISSUE_RECEIPT', 'Reissue Receipt'), ('TRANSACTION_CONFIRMED', 'Transaction Confirmed'), ('AGENT_LOGIN', 'Agent Login'), ('AGENT_LOGOUT', 'Agent Logout')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='sales_audit_action_4ca69e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rechargedenomination',
            index=models.Index(fields=['product_type', 'is_active'], name='sales_recha_product_b64a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargedenomination',
            index=models.Index(fields=['value'], name='sales_recha_value_4f5c54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rechargedenomination',
            unique_together={('company', 'product_type', 'value')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='sales_trans_status_5c4a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['agent', 'created_at'], name='sales_trans_agent_i_50ea06_idx'),
        ),
    ]
