# Generated by Django 5.2.10 on 2026-01-30 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('WEB', 'Web'), ('POS', 'POS')], db_index=True, default='WEB', max_length=10),
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
