# Generated by ChatGPT patch: add receipt_payload snapshot field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_transaction_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receipt_payload_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
