# Generated by Django 5.2.10 on 2026-01-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_adminpermission_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermission',
            name='can_add_agents',
            field=models.BooleanField(default=False),
        ),
    ]
