# Generated by Django 4.2 on 2026-01-31 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminpermission_can_add_agents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpermission',
            options={'verbose_name': 'Admin Permission', 'verbose_name_plural': 'Admin Permissions'},
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='admin',
            field=models.OneToOneField(help_text='يرتبط فقط بالمستخدمين من نوع ADMIN', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_add_agents',
            field=models.BooleanField(default=False, help_text='إضافة وكيل جديد'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_edit_agents',
            field=models.BooleanField(default=False, help_text='تعديل بيانات الوكلاء'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_edit_commissions',
            field=models.BooleanField(default=False, help_text='تعديل العمولات'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_view_agents',
            field=models.BooleanField(default=True, help_text='عرض قائمة الوكلاء'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False, help_text='عرض سجل العمليات'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_view_commissions',
            field=models.BooleanField(default=False, help_text='عرض العمولات'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='عرض التقارير'),
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='preset',
            field=models.CharField(choices=[('CUSTOM', 'مخصص'), ('READ_ONLY', 'قراءة فقط'), ('MANAGER', 'مدير'), ('ACCOUNTANT', 'محاسب')], db_index=True, default='CUSTOM', max_length=20),
        ),
    ]
