# Generated by Django 5.2.10 on 2026-02-06 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_is_supe_4686ba_idx',
        ),
        migrations.AlterField(
            model_name='adminpermission',
            name='admin',
            field=models.OneToOneField(help_text='يرتبط فقط بالمستخدمين من نوع ADMIN', limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SELL', 'Sell Recharge'), ('CONFIRM', 'Confirm Recharge'), ('REISSUE_RECEIPT', 'Reissue Receipt'), ('ADD_AGENT', 'Add Agent'), ('RESET_AGENT_PASSWORD', 'Reset Agent Password'), ('SUSPEND_AGENT', 'Suspend Agent'), ('ACTIVATE_AGENT', 'Activate Agent'), ('DELETE_AGENT', 'Delete Agent'), ('ADJUST_BALANCE', 'Adjust Balance'), ('UPDATE_DEFAULT_COMMISSION', 'Update Default Commission'), ('ADD_AGENT_COMMISSION', 'Add Agent Commission'), ('ADD_ADMIN', 'Add Admin'), ('RESET_ADMIN_PASSWORD', 'Reset Admin Password'), ('DISABLE_ADMIN', 'Disable Admin'), ('DELETE_ADMIN', 'Delete Admin'), ('TOGGLE_SUPER_ADMIN', 'Toggle Super Admin'), ('UPDATE_ADMIN_PERMISSIONS', 'Update Admin Permissions')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='transaction_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent')], db_index=True, default='AGENT', max_length=10),
        ),
    ]
