# Generated by Django 5.2.10 on 2026-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SELL', 'Sell Recharge'), ('CONFIRM', 'Confirm Recharge'), ('REISSUE_RECEIPT', 'Reissue Receipt'), ('ADD_AGENT', 'Add Agent'), ('RESET_AGENT_PASSWORD', 'Reset Agent Password'), ('SUSPEND_AGENT', 'Suspend Agent'), ('ACTIVATE_AGENT', 'Activate Agent'), ('DELETE_AGENT', 'Delete Agent'), ('ADJUST_BALANCE', 'Adjust Balance'), ('UPDATE_DEFAULT_COMMISSION', 'Update Default Commission'), ('ADD_AGENT_COMMISSION', 'Add Agent Commission'), ('ADD_ADMIN', 'Add Admin'), ('RESET_ADMIN_PASSWORD', 'Reset Admin Password'), ('DISABLE_ADMIN', 'Disable Admin'), ('DELETE_ADMIN', 'Delete Admin'), ('TOGGLE_SUPER_ADMIN', 'Toggle Super Admin'), ('UPDATE_ADMIN_PERMISSIONS', 'Update Admin Permissions'), ('UPDATE_AGENT_USERNAME', 'Update Agent Username'), ('TOGGLE_SHOW_PROFIT', 'Toggle Show Profit Setting')], db_index=True, max_length=50),
        ),
    ]
