# Generated by Django 5.2.10 on 2026-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermission',
            name='can_view_profit',
            field=models.BooleanField(default=True, help_text='عرض صفحة الأرباح'),
        ),
    ]
