# Generated by ChatGPT on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pos_device_id",
            field=models.CharField(
                max_length=128,
                blank=True,
                null=True,
                help_text="Bound POS device identifier (e.g., Sunmi serial/Android ID)",
            ),
        ),
    ]
