# Generated by Django 5.2.10 on 2026-02-06 09:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agentcommission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='defaultcommission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Custom commission in IQD', max_digits=12),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agentcommission',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defaultcommission',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Commission in IQD', max_digits=12),
        ),
        migrations.AddField(
            model_name='defaultcommission',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='defaultcommission',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['code'], name='commissions_code_6e2bde_idx'), models.Index(fields=['is_active'], name='commissions_is_acti_b03448_idx')],
            },
        ),
        migrations.AlterField(
            model_name='agentcommission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.company'),
        ),
        migrations.AlterField(
            model_name='defaultcommission',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.company'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['agent', 'company', 'denomination'], name='commissions_agent_i_33f7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='agentcommission',
            index=models.Index(fields=['is_active'], name='commissions_is_acti_41bb7a_idx'),
        ),
        migrations.AddIndex(
            model_name='defaultcommission',
            index=models.Index(fields=['company', 'denomination'], name='commissions_company_cc7c59_idx'),
        ),
        migrations.AddIndex(
            model_name='defaultcommission',
            index=models.Index(fields=['is_active'], name='commissions_is_acti_dff68e_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentcommission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('agent', 'company', 'denomination'), name='unique_active_agent_commission'),
        ),
        migrations.AddConstraint(
            model_name='defaultcommission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'denomination'), name='unique_active_default_commission'),
        ),
        migrations.RemoveField(
            model_name='agentcommission',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='defaultcommission',
            name='commission_amount',
        ),
    ]
